version: "3.4"

services:
  
  
  build:
    container_name: gemp_app
    build: 
      context: .
      dockerfile: gemp_app.Dockerfile
    image: gemp_app
    expose:
      - "80"
      - "8080"
    restart: always
    ports:
        # target means in the container
      - target: 80
        # published is what's on the host machine
        published: 1337
    volumes:
       - type: bind
         source: ../gemp-lotr-async/src/main/web
         target: /etc/gemp-lotr/web
       - type: bind
         source: ../../gemp-lotr
         target: /etc/gemp-lotr
       - type: bind
         source: ../gemp-lotr-async/src/main/web
         target: /var/www/localhost/htdocs/gemp-lotr #/etc/apache2/htdocs/gemp-lotr
    networks:
      gemp_net:
        ipv4_address: 172.28.1.1
    tty: true
    command: nohup java -jar /etc/gemp-lotr/gemp-lotr-async/target/web.jar &


  db:
    container_name: gemp_db
    build: 
      context: ..
      dockerfile: docker/gemp_db.Dockerfile
    image: gemp_db
    ports:
        # target means in the container
      - target: 3306
        # published is what's on the host machine
        published: 3307
    restart: always
    volumes:
       - type: bind
         source: ../../database
         target: /var/lib/mysql
    networks:
      gemp_net:
        ipv4_address: 172.28.1.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gemp_db
      MYSQL_USER: gempuser
      MYSQL_PASSWORD: gemppassword
      
  
networks:
  gemp_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16